name: Terraform Automation

on:
  pull_request:
    paths:
      - '**.tf'
      - '**.tfvars'
      - '.terraform.lock.hcl'
      - '.github/workflows/terraformworkflowstrategy.yml'
  push:
    branches:
      - mybranch
    paths:
      - '**.tf'
      - '**.tfvars'
      - '.terraform.lock.hcl'
      - '.github/workflows/terraformworkflowstrategy.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform:
    name: Terraform ${{ matrix.command }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        command: [validate, plan]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Terraform aws configuration setup
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWSACCESSKEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRETS_ACCESS_KEY }}
        run: aws configure list

      - name: Initialize Terraform
        run: terraform init 

    
      - name: Generate Terraform plan
        if: matrix.command == 'plan'
        run: terraform plan -input=false -no-color 